//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dragon.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             102
#define IDD_DRAGON_DIALOG               103
#define ID_D_LIST                       107
#define ID_MSUBSTR_FILTER               111
#define ID_MSUBSTR_UNFILTER             112
#define ID_MSUBSTR_LIST                 113
#define ID_NEWTABLE                     114
#define IDB_FILELARGE                   115
#define IDB_FILESMALL                   116
#define IDB_RIBBON_FILE_SMALL           117
#define IDR_POPUP_EDIT                  118
#define ID_GAHTML                       119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDD_SELECT_PEOPLE               130
#define IDD_DATE                        133
#define IDD_SELECTED_FILES              135
#define IDD_SELECTONE                   137
#define IDD_SELECT_PARENT               139
#define IDD_SELECTHTMLFILE              141
#define IDD_INPUT_GEDCOM                145
#define IDD_TABLE_FIRSTNAMES            147
#define IDD_MORESPOUSES                 148
#define IDD_TITLES                      150
#define IDD_SELECTGENERATION            151
#define IDD_GAERRORS                    152
#define IDD_HTML_DESCENDANTS            153
#define IDD_HTML_MARRIAGES              154
#define IDD_HTML_SPOUSES                155
#define IDD_HTML_SPSP                   156
#define IDD_GET_STRING                  159
#define IDD_TABLE_HTML                  160
#define IDR_TABLE_HTML                  161
#define IDD_INFO_DB                     162
#define IDD_TABLE_MARRIAGES             164
#define IDD_TABLE_TABLES                167
#define IDD_FILTER                      182
#define IDD_TABLE_FILES                 183
#define IDD_TABLE_GATABLES              193
#define IDD_HTML_EDITLINE               194
#define IDD_COLUMNSLIST                 195
#define IDR_TABLE_TABLES                196
#define IDD_COMPARE_ENTRIES             199
#define ID_VIEW_APPLOOK_WIN_2000        201
#define ID_VIEW_APPLOOK_OFF_XP          202
#define ID_VIEW_APPLOOK_WIN_XP          203
#define ID_VIEW_APPLOOK_OFF_2003        204
#define ID_VIEW_APPLOOK_VS_2005         205
#define ID_VIEW_APPLOOK_VS_2008         206
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   207
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  208
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 209
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   210
#define ID_VIEW_APPLOOK_WINDOWS_7       211
#define IDR_TABLE_FIRSTNAMES            212
#define IDD_SELECTFAMILY                213
#define IDD_SELECTFAMILYNAME            214
#define IDD_SELECTTABLENAME             215
#define IDD_SELECTTABLE                 216
#define IDD_SELECTTWO                   217
#define IDD_SELECTSTRING                218
#define IDR_MAIN_GEDCOM                 219
#define IDR_MAIN_EMPTY                  220
#define IDD_TABLE_PEOPLE                221
#define IDR_TABLE_PEOPLE_GEDCOM         223
#define IDR_TABLE_PEOPLE_HTML           225
#define IDR_MAIN_GAHTML                 226
#define IDR_MAIN_MANUAL                 227
#define IDR_TABLE_PEOPLE_MANUAL         229
#define IDR_TABLE_GATABLES              231
#define IDR_DROPDOWN_EDIT               235
#define IDD_EDIT_TABLE                  237
#define IDD_SETUP                       239
#define IDD_SAMEPARAMS                  241
#define IDD_FIRSTLETTER                 242
#define IDR_TABLE_FILES                 243
#define IDD_EDIT_FIRSTNAME              244
#define IDD_LANGUAGES                   245
#define IDD_NAMESPARAM                  246
#define IDD_TABLE_PLACES                247
#define IDR_HTML_DESCENDANTS            253
#define IDR_HTML_MARRIAGES              254
#define IDR_HTML_SPOUSES                255
#define IDR_HTML_SPSP                   256
#define IDB_TREE                        262
#define IDD_CHECK_PARENTS               267
#define IDD_BRACKETS                    268
#define IDR_ACCELERATOR                 269
#define IDD_MESSAGE                     270
#define IDR_RELATIVES                   276
#define IDD_TABLE_IDENTICALPEOPLE       278
#define IDR_SQUARE                      283
#define IDR_ROUND                       284
#define IDD_CHECK_PARAM4                285
#define IDD_HTML_EDITLINES              288
#define IDD_CHECK_SAMENAMEAND           289
#define IDD_CHECK_SAMESPOUSES           291
#define IDR_DROPDOWN_HTML               299
#define IDD_FAMILY                      305
#define IDS_EDIT_MENU                   306
#define IDD_CHECK_MOTHERDEATH           308
#define IDD_CHECK_LIFESPAN              310
#define IDD_GETLASTFIRST                311
#define IDD_CHECK_DATEFORMAT            312
#define IDD_CHECK_PARAM3                313
#define IDD_SELECTFATHER                315
#define IDD_SELECTMOTHER                316
#define IDD_EDIT_PEOPLE                 317
#define IDD_GETPEOPLE                   318
#define IDD_EDIT_MARRIAGE               319
#define IDD_UNITED_ENTRIES              320
#define IDR_HTMLINES                    322
#define IDD_GET_MARRIAGE                324
#define IDD_CHECK_FATHERDEATH           325
#define IDR_CHECK_NAMES                 326
#define IDD_UNITED_ENTRIES_DIFFERENT    328
#define IDD_UNITED_ENTRIES_ERRORS       329
#define IDD_CHECK_SPOUSES_DIFF          330
#define IDD_CHECK_PARAM                 331
#define IDD_CHECK_PARENTCHILD           332
#define IDD_CHECK_SPOUSE_AGE            333
#define IDD_CHECK_SPOUSES_SEX           334
#define IDD_CHECK_PARAM0                335
#define IDD_CDialogRichText             336
#define IDD_INPUTERRORS                 338
#define IDR_INPUTERRORS                 339
#define IDD_CHECK_NAMES                 340
#define ID_DESCENDANTS_TABLE            341
#define IDD_CHECK_MOTHERINDEX           342
#define ID_ONE_TABLE                    343
#define ID_DIFFERENT_TABLE              344
#define IDD_PICTURES                    345
#define ID_UNITED_TABLE                 346
#define IDD_EDIT_BLOB                   347
#define ID_GEDCOM_PEOPLE                348
#define IDD_MARRIAGEEDIT                349
#define ID_GEDCOM_FAMILIES              350
#define IDD_TABLE_BLOBS                 351
#define ID_GEDCOM_VINDI                 352
#define IDR_TABLE_BLOBS                 353
#define ID_GEDCOM_INDIFAMS              354
#define IDR_DROPDOWN_EDITM              355
#define ID_GEDCOM_VFAM                  356
#define IDD_GEDCOM_OUT                  357
#define ID_SQUARE_BRACKETS              358
#define ID_BRACKETS_CSALAD              359
#define IDD_SAME_NAME                   360
#define IDR_UNITED_ENTRIES0             361
#define IDR_DROPDOWN_SPOUSE             362
#define IDR_UNITED_ENTRIES2             363
#define IDD_SAVEFIRSTNAME               364
#define IDD_EDIT_COMMENT                368
#define IDD_ASCENDANTS_PAINT            369
#define IDC_COORDINATES                 370
#define IDC_STATUS                      371
#define IDD_SAME_COUPLES                372
#define IDR_CHECK_SAMESPOUSES           374
#define IDR_SAME_COUPLES                375
#define ID_CXHECK_MORESPOUSES           375
#define IDR_DROPDOWN_SAMECOUPLES        376
#define ID_CHECK_LIFETIME               376
#define IDD_CHECK_GENERATIONS           377
#define ID_CHECK_MORESPOUSES            377
#define IDD_SAMEPEOPLE                  380
#define IDD_DISPLAY_INFO                381
#define IDD_DESCENDANTS_NEW             383
#define IDD_DESCENDANTS_LINEARTABLE     383
#define IDD_FILTERLOOP                  384
#define IDD_DESCENDANTS_FULL            385
#define IDD_DESCENDATS_UNIQUE           386
#define IDD_DESCENDANTS_UNIQUE          386
#define IDR_CHECK_DATES                 387
#define IDR_RIBBON                      388
#define IDD_CONTRACTED_COUPLES          389
#define IDD_CONTRACT_DBP_DLG            391
#define IDD_TABLECOUPLES                392
#define IDD_CHECK_FAMILYDATES           394
#define IDR_CHECK_FAMILYDATES           395
#define IDD_CHECK_FAMILYDATES_START     396
#define IDR_DROPDOWN_PEOPLE             400
#define IDR_DROPDOWN_FAMILIES           401
#define IDR_TABLE_FAMILIES              402
#define IDR_HTML_EDITLINES              403
#define IDR_INFO                        404
#define IDD_RELATIVES                   409
#define IDD_SELECTFROMPEOPLE            410
#define IDD_UNREFERENCEDITEMS           412
#define IDR_DROPDOWN_NOTEBOOK           413
#define IDR_DROPDOWN_GEDCOM             414
#define IDD_CHECK_FATHERCHILDREN        416
#define IDD_CHECK_NUMOFSPOUSES          426
#define IDD_CHECK_ORDERWIFE             428
#define IDD_INPUTGA                     435
#define IDD_ASCENDANTS                  436
#define IDD_KEKULE                      437
#define IDR_DROPDOWN_DBP_HTML           482
#define IDR_DROPDOWN_RELATION_HTML      483
#define IDR_BRACKETS                    487
#define IDR_DROPDOWN_SEX                488
#define IDR_DROPDOWN_SPOUSEORDER        489
#define IDR_DROPDOWN_MARRIAGES          490
#define IDR_DROPDOWN_MARRIAGES_GA       491
#define IDD_COMPARE_ASC                 492
#define IDD_DESCENDANTS_PARAM           506
#define IDD_DESCENDANTS                 507
#define IDD_NOTEPAD                     508
#define IDD_UNITED_ENTRIES_UNITED       515
#define IDR_UNITED_ENTRIES1             521
#define IDR_DROPDOWN_UNITED_UNITED      523
#define IDR_DROPDOWN_UNITED_ERRORS      524
#define IDR_DROPDOWN_UNITED_DIFFERENT   525
#define IDR_DROPDOWN_PEOPLE_GA          526
#define IDR_DROPDOWN_PEOPLE_HTML        527
#define IDR_DROPDOWN_MARRIAGES_GEDCOM   533
#define IDR_DROPDOWN_2ROKONOK           537
#define IDD_SELECTLINENUMBER            541
#define IDD_ASCENDANTS_LINEAR           546
#define IDD_ASCENDANTS_FULL             548
#define IDD_ASCENDANTS_UNIQUE           550
#define IDR_DROPDOWN_ASCENDANTS         552
#define IDR_ASCENDANTS_LINEAR           553
#define IDR_ASCENDANTS_PAINT            557
#define IDR_DROPDOWN_CHECKNAMES         564
#define IDR_TABLE_MARRIAGES             565
#define IDD_UNITED_ENTRIES_X            568
#define IDR_DESCENDANTS_LINEAR          574
#define IDC_LIST                        1000
#define IDC_LAST_NAME                   1002
#define IDC_FIRST_NAME                  1003
#define IDC_BIRTH_PLACE                 1004
#define IDC_BIRTH_DATE                  1005
#define IDC_DEATH_PLACE                 1008
#define IDC_DEATH_DATE                  1009
#define IDC_STATIC_FATHER               1010
#define IDC_STATIC_MOTHER               1011
#define IDC_COMMENT                     1018
#define IDC_COMBO_SEX                   1019
#define IDC_SEARCH                      1022
#define IDC_EDIT_DATE                   1023
#define IDC_TEXTEDITOR                  1024
#define IDC_EDIT_COMMENT                1025
#define IDC_VIEWER                      1026
#define IDC_EDIT_ROOT                   1028
#define IDC_EDIT_AG                     1030
#define IDC_STATIC_WIFE                 1033
#define IDC_DATETIMEPICKER1             1041
#define IDC_BUTTON_CLEAR                1042
#define IDC_STATIC_TEXTEDITOR           1043
#define IDC_BUTTON_DEFAULT              1044
#define IDC_SELECTONE                   1045
#define IDC_EDIT_PLACE                  1047
#define IDC_DATABASE                    1051
#define IDC_EDIT_ORDERHUSBAND           1053
#define IDC_EDIT_ORDERWIFE              1054
#define IDC_STATIC_PARENT               1056
#define IDC_PARENT                      1057
#define IDC_EDIT                        1059
#define IDC_EDIT_K                      1060
#define IDC_COMBO_TYPE                  1064
#define IDC_COMBO                       1065
#define IDC_HTMLFILESPEC                1067
#define IDC_HUSBAND                     1074
#define IDC_WIFE                        1075
#define IDC_STATIC_GED                  1081
#define IDC_CHECK_CRLF                  1082
#define IDC_STATIC_DB                   1086
#define IDC_CAPTION                     1093
#define IDC_LISTHTML                    1094
#define IDC_HTML                        1095
#define IDC_TABLES                      1096
#define IDC_PEOPLES                     1097
#define IDC_MARRIAGES                   1098
#define IDC_DBSIZE                      1099
#define IDC_CREATED                     1100
#define IDC_MODIFIED                    1101
#define IDC_ACCESSED                    1102
#define IDC_DBSIZE2                     1103
#define IDC_CREATED2                    1105
#define IDC_MODIFIED2                   1107
#define IDC_ACCESSED2                   1109
#define IDC_DBSIZEBLOB                  1110
#define IDC_CREATEDBLOB                 1111
#define IDC_MODIFIEDBLOB                1112
#define IDC_ACCESSEDBLOB                1113
#define IDC_STATIC_SQLITE               1114
#define IDC_STATIC_BUILT                1116
#define IDC_CONDITION1                  1117
#define IDC_CONDITION2                  1118
#define IDC_FILTER_ALL                  1119
#define IDC_FILTER_LAST                 1120
#define IDC_FAMILIES                    1121
#define IDC_CHECK_UNDERLINE             1122
#define IDC_FAMILYNAME                  1125
#define IDC_TABLE_NAME                  1141
#define IDC_FREELIST                    1143
#define IDC_FREELIST_COUNT              1144
#define IDC_FREELISTBLOB                1146
#define IDC_FREELISTBLOB_COUNT          1147
#define IDC_FREELISTSYSTEM_COUNT        1149
#define IDC_STATIC_GA                   1161
#define IDC_STATIC_HUSBAND              1186
#define IDC_EDIT_FAMILYNAME             1192
#define IDC_FATHERAGEMIN                1193
#define IDC_EDIT_ALIAS                  1193
#define IDC_EDIT_AUXNAME                1194
#define IDC_FATHERAGEMAX                1195
#define IDC_COMBO_ROMAN                 1196
#define IDC_MOTHERAGEMIN                1197
#define IDC_MOTHERAGEMAX                1199
#define IDC_FIRSTNAME                   1203
#define IDC_LANGUAGE                    1206
#define IDC_ORIGIN                      1207
#define IDC_MEANING                     1208
#define IDC_STATIC_LANGUAGE             1210
#define IDC_FILE                        1213
#define IDC_FILESPEC                    1214
#define IDC_STATIC_LANG                 1216
#define IDC_PICTURE                     1222
#define IDC_BUTTON                      1223
#define IDC_CHECK_CONNECT               1237
#define IDC_CHECK_WOMAN                 1238
#define IDC_STATIC_ITERATIONS           1240
#define IDC_RADIO_LOOP                  1245
#define IDC_RADIO_LOOP1                 1246
#define IDC_INFO                        1258
#define IDC_STATIC_NAMES                1265
#define IDC_CHECK_NN                    1269
#define IDC_RADIO_LIST                  1273
#define IDC_RADIO_LIST1                 1274
#define IDC_RADIO_ALL                   1276
#define IDC_RADIO_ALL1                  1277
#define IDC_RADIO_LIST2                 1282
#define IDC_EDIT_NAME                   1284
#define IDC_RADIOLIST                   1286
#define IDC_DATE                        1288
#define IDC_NAMECHANGED                 1290
#define IDC_RADIO_ALL2                  1293
#define IDC_RADIO                       1301
#define IDC_RADIO2                      1302
#define IDC_RADIO3                      1303
#define IDC_STATIC_TABLE                1309
#define IDC_TABLE                       1310
#define IDC_PLACE                       1311
#define IDC_TITOLO                      1325
#define IDC_STATIC_MARRIAGES            1327
#define IDC_STATIC_SPOUSE               1328
#define IDC_COMBO_SPEC                  1334
#define IDC_COMBO_COMMENT               1337
#define IDC_COMBO_NAME                  1338
#define IDC_COMBO_WORDER                1341
#define IDC_COMBO_HORDER                1342
#define IDC_PROGRAM                     1344
#define IDC_PLATFORM                    1345
#define IDC_FUNCTION1                   1355
#define IDC_FUNCTION2                   1356
#define IDC_BLOBS                       1359
#define IDC_CHECK_BOLD                  1368
#define IDC_CHECK_DISPLAY               1373
#define IDC_PRIMARY                     1374
#define IDC_NUMOFFG                     1381
#define IDC_NUMOFMG                     1382
#define IDC_NUMOFFA                     1383
#define IDC_NUMOFMA                     1384
#define IDC_NUMOFFDA                    1385
#define IDC_TABLEHEADER_OUT             1386
#define IDC_NUMOFMDA                    1387
#define IDC_COMBO_JOINT                 1388
#define IDC_TABLEHEADER_IN              1389
#define IDC_BUTTON_DELETE               1390
#define IDC_REINDEX                     1391
#define IDC_VIEW                        1392
#define IDC_SZLUHA                      1393
#define IDC_TITLE                       1394
#define IDC_REINDEX_SYSTEM              1395
#define IDC_REINDEX_BLOB                1398
#define IDC_STATIC_COMMENT              1399
#define IDC_BUTTON_SAVE                 1401
#define IDC_BUTTON_VIEW                 1402
#define IDC_STATIC_VIEWER               1403
#define IDC_CNT_W                       1404
#define IDC_BIRTHH                      1406
#define IDC_BIRTHW                      1407
#define IDC_CNT_H                       1408
#define IDC_INTEGRITY                   1410
#define IDC_INTEGRITYBLOB               1411
#define IDC_ANSI                        1412
#define IDC_UTF8                        1413
#define IDC_INTEGRITYSYSTEM             1414
#define IDC_FILENAME                    1415
#define IDC_STATIC_FILESPEC             1416
#define IDC_PATH                        1417
#define IDC_VACUUM                      1418
#define IDC_VACUUM_SYSTEM               1419
#define IDC_VACUUM_BLOB                 1420
#define IDC_PHOTOS                      1422
#define IDC_SPIN                        1424
#define IDC_BIRTH_COMBO                 1438
#define IDC_DEATH_COMBO                 1439
#define IDC_VILLERS                     1470
#define IDC_TUPIGNY                     1476
#define IDC_STATIC_BLOB                 1492
#define IDC_STATIC_SYSTEM               1493
#define IDC_NEXT                        1500
#define IDC_EDIT_POSTERIOR              1507
#define IDC_MODIFY                      1509
#define IDC_MAXLIFESPAN                 1518
#define IDC_MINAGEHATWEDD               1521
#define IDC_MAXAGEHATWEDD               1522
#define IDC_MINDIFFFC                   1523
#define IDC_MAXAGEWATWEDD               1524
#define IDC_MAXDIFFFC                   1526
#define IDC_MINDIFFMC                   1527
#define IDC_MAXDIFFMC                   1528
#define IDC_MINAGEWATWEDD               1529
#define IDC_BUTTON_SELECT               1541
#define IDC_EDIT_TITLE                  1542
#define IDC_STATIC_EDITBOX              1545
#define IDC_STATIC_GYUJTO               1546
#define IDC_LIST1                       1547
#define IDC_LIST2                       1548
#define IDC_LIST3                       1549
#define IDC_LIST4                       1550
#define IDC_COMBO_FONTSIZE              1554
#define IDC_BUTTON_MEN                  1557
#define IDC_BUTTON_WOMEN                1558
#define IDC_BUTTON_BISEX                1559
#define IDC_STATIC_PEOPLE               1560
#define IDC_STATIC_CHILDREN             1565
#define IDC_STATIC_SIBLINGS             1566
#define IDC_LISTCTRL_SIBLINGS           1570
#define IDC_LISTCTRL_CHILDREN           1571
#define IDC_LISTCTRL_MARRIAGES          1573
#define IDC_LISTCTRL_PARENTS            1574
#define IDC_STATIC_KERESS               1577
#define IDC_STATIC_BACKGROUND           1578
#define IDC_BUTTON_BGNCOLOR             1579
#define IDC_CHECK_CAPITAL               1582
#define IDC_COMBO_DESCATTRIB            1587
#define IDC_RADIO_NOFAMILYNAME          1588
#define IDC_RADIO_FAMILYNAME            1589
#define IDC_RADIO_FAMILYNAMEUP          1590
#define IDC_EDIT_WIDTH                  1591
#define IDC_STATIC_WIDTH                1592
#define IDC_CHECK_REPEATED              1593
#define IDC_STATIC_SEARCH               1594
#define IDC_CHECK_LIST_MCHILDREN        1595
#define IDC_STATIC_NEXT                 1620
#define IDC_STATIC_KERES                1621
#define IDC_CHECK_FOLYT                 1623
#define IDC_BUTTON_FAMILY               1625
#define IDC_BUTTON_TABLE                1626
#define IDC_BUTTON_FILE                 1627
#define IDC_GED                         1628
#define IDC_GROUPBOX_DESC               1629
#define IDC_GROUPBOX_ATTRIB             1630
#define IDC_GROUPBOX_PRINT              1631
#define IDC_GROUPBOX_CODE               1632
#define IDC_GROUPBOX_NUM                1633
#define IDC_STATIC_NAME                 1634
#define IDC_STATIC_ATTRIB               1635
#define IDC_STATIC_PRINT                1636
#define IDC_STATIC_CODE                 1637
#define IDC_STATIC_NUM                  1638
#define IDC_STATIC_FAMILY_INLINE        1643
#define IDC_STATIC_FAMILYNAME_NO        1644
#define IDC_STATIC_FAMILYNAME_UP        1645
#define IDC_STATIC_ORAND                1646
#define IDC_GENMAX                      1648
#define IDC_DEFAULT                     1649
#define IDC_GROUP_LIST                  1652
#define IDC_GROUP_APAI                  1659
#define IDC_GROUP_ANYAI                 1660
#define IDC_GROUP_ANYAI_TEXT            1661
#define IDC_GROUP_APAI_TEXT             1662
#define IDC_GROUP_DATA                  1663
#define IDC_GROUP_DATA_TEXT             1664
#define IDC_GROUP_KEKULE_TEXT           1669
#define IDC_BUTTON_PIRAMID              1673
#define IDC_BUTTON_BRANCHES             1674
#define IDC_BUTTON_APAI                 1675
#define IDC_GROUP_KEKULE                1676
#define IDC_GROUP_LIST_TEXT             1677
#define IDC_BUTTON_ANYAI                1678
#define IDC_GROUP_MAS                   1679
#define IDC_GROUP_MAS_TXT               1680
#define IDC_GROUP_OTHER                 1681
#define IDC_GROUP_OTHER_TXT             1682
#define IDC_DIRECT_FATHER_ASCENDANTS    1683
#define IDC_DIRECT_MOTHER_ASCENDANTS    1684
#define IDC_DIRECT_COUPLESF             1685
#define IDC_GROUP_INFO                  1686
#define IDC_GROUP_INFO_TEXT             1687
#define IDC_EDIT_G                      1688
#define IDC_DIRECT_COUPLESM             1689
#define IDC_GENMAX_TEXT                 1690
#define IDC_RADIO_ORDER                 1691
#define IDC_GROUP_ORDER                 1692
#define IDC_RADIO_ORDER1                1693
#define IDC_GROUP_ORDER_TEXT            1694
#define IDC_CHECK_PEER                  1695
#define IDC_RADIO_ONE1                  1696
#define IDC_RADIO_ONE                   1697
#define IDC_STATIC_OUTPUT               1700
#define IDC_GROUPBOX_OUTPUT             1701
#define IDC_GROUP_CONTENT               1702
#define IDC_STATIC_CONTENT              1703
#define IDC_EDIT_NUM                    1706
#define IDC_ATTENTION                   1708
#define IDC_STATIC_NUMBER               1712
#define IDC_GROUP_GENERATIONS           1714
#define IDC_GROUP_GENERATIONS_TEXT      1715
#define IDC_GROUP_ASCENDANTS            1716
#define IDC_GROUP_ASCENDANTS_TEXT       1717
#define IDC_NUMOFGF                     1720
#define IDC_NUMOFGM                     1721
#define IDC_NUMOFAF                     1722
#define IDC_NUMOFAM                     1723
#define IDC_NUMOFGDF                    1724
#define IDC_NUMOFGDM                    1725
#define IDC_PIRAMID                     1727
#define IDC_REPEATED_ALL                1744
#define IDC_REPEATED_FIRST              1745
#define IDC_REPEATED_FATHER             1746
#define IDC_REPEATED_COLOR              1747
#define IDC_GROUP_REPEATED              1748
#define IDC_STATIC_REPEATED             1749
#define IDC_EDIT_SEARCH                 1756
#define IDC_TAB                         1757
#define IDC_LIST_UNITED                 1758
#define IDC_RICHEDIT                    1765
#define IDC_LIST_DIFFERENT              1767
#define IDC_LIST_ERROR                  1768
#define IDC_INPUT                       1779
#define IDC_UNITED                      1780
#define IDC_UNITED2                     1781
#define IDC_MAPPA                       1791
#define IDC_STATIC_LINE                 1793
#define IDC_STATIC_ROWID                1794
#define IDC_STATIC_R                    1795
#define IDC_STATIC_L                    1796
#define IDC_BUTTON_LINE                 1799
#define IDC_COMBO_HTMTXT                1800
#define IDC_STATIC_INPUTVERSION         1802
#define IDC_CHECK_COLOR                 1810
#define IDC_STATIC_LINENUMBER           1811
#define IDC_EDIT_LINENUMBER             1812
#define IDC_STATIC_NUMBEROFLINES        1813
#define IDC_EDIT_NUMBEROFLINES          1814
#define IDC_CHECK_FIRST_BOLD            1816
#define IDC_STATIC_ENOUGH               1818
#define IDC_BOX_LINEAR                  1819
#define IDC_INPUT_FILE                  1819
#define IDC_LINEAR_TITLE                1820
#define IDC_LINEAR                      1823
#define IDC_CHECK_ABC                   1824
#define IDC_CHECK_PRINTABLE             1828
#define IDC_CHECK_ORDINAL               1829
#define IDC_ORDER_INPUT                 1831
#define IDC_ORDER_LENGTH                1833
#define IDC_ORDER_DECREASING            1834
#define IDC_ORDER_TXT                   1835
#define IDC_ORDER_BIRTH                 1836
#define IDC_LINEAR_SQLITETABLE          1837
#define IDC_LIST_FULL                   1839
#define IDC_LIST_UNIQUE                 1840
#define IDC_INPUT_DATE                  1848
#define IDC_INPUT_VERSION               1849
#define IDC_UNITED_VERSION              1850
#define IDC_LIST5                       1851
#define IDC_LIST6                       1852
#define IDC_LIST_X                      1853
#define IDC_LISTCOLUMNS                 11044
#define ID_EDIT_INSERT                  32771
#define ID_EDIT_UPDATE                  32772
#define ID_EDIT_DELETE                  32773
#define ID_LISTS_ROWID                  32774
#define ID_CONV_16TO8                   32775
#define ID_FULLNAME                     32776
#define ID_SELECTED_FILES               32780
#define ID_INPUT_SZLUHA                 32781
#define ID_FILTER_UNFILTER              32785
#define ID_INPUTFILES                   32787
#define ID_FILTER_NOSPOUSE              32806
#define ID_TABLE_BOYS                   32855
#define ID_FILTER_FIRSTNAME             32878
#define ID_FILTER_TABLE                 32906
#define ID_UNFILTER                     32916
#define ID_FILTER_SUBSTRING             32969
#define ID_OPEN_HTML                    32980
#define ID_FILTER_FAMILY                33015
#define ID_FILTER_MAN                   33039
#define ID_EXPORT_ALL                   33068
#define ID_EXPORT_SELECTED              33069
#define ID_DISPLAY_TABLES               33114
#define ID_LIST_SELECTED                33156
#define ID_CHECK_USED                   33190
#define ID_DESCENDANT_FILE              33193
#define ID_FILTER_INCIDENCE             33256
#define ID_FILTER_WOMEN                 33259
#define ID_FILTER_BISEX                 33269
#define ID_DESCENDANT_TABLE             33275
#define ID_SPOUSES_SEX                  33278
#define ID_SS_FILE                      33281
#define ID_SS_TABLE                     33283
#define ID_SS_LINE                      33285
#define ID_INPUT_GAHTML_LINE            33291
#define ID_INPUT_GAHTML_FROMLINE        33293
#define ID_MARRIAGES_FILE               33303
#define ID_MARRIAGES_TABLE              33304
#define ID_MARRIAGES_LINE               33305
#define ID_FILTER_CORRECT               33310
#define ID_OPEN_DB                      33357
#define ID_DISPLAY_INDIVIDUALS          33389
#define ID_DISPLAY_MARRIAGES            33392
#define ID_INFO_ONPROGRAM               33404
#define ID_DATABASE_INFORMATION         33406
#define ID_DISPLAY_FILESTABLE           33407
#define ID_FILTER_NODESCENDANT          33417
#define ID_FILTER_NOPARENTS             33418
#define ID_FILTER_MEN                   33420
#define ID_FILTER_FILE                  33438
#define ID_FILTER_INDIVIDUAL            33445
#define ID_FILTER_LASTNAME              33448
#define ID_FILTER_ANCESTORS             33457
#define ID_EXTRACTTABLE                 33552
#define ID_INFO                         33592
#define ID_FILTER_FOLYT                 33594
#define ID_REINDEX                      33618
#define ID_USERMANUAL                   33619
#define ID_AZONOSEMBER                  33631
#define ID_GEDCOM_INDI                  33637
#define ID_DESCENDANT_LINE              33644
#define ID_AZONOSEMBER_CONC             33650
#define ID_BROWSER                      33691
#define ID_TEXTEDITOR                   33692
#define ID_SELECT_TABLE                 33694
#define ID_READTXTFILE                  33698
#define ID_LANGUAGES                    33700
#define ID_FILTER_LANGUAGE              33703
#define ID_GROUPBY_LASTNAME             33719
#define ID_GROUPBY_FIRSTNAME            33720
#define ID_GROUPBY_BIRTHPLACE           33722
#define ID_GROUPBY_DEATHPLACE           33724
#define ID_GROUPBY_TITOLO               33727
#define ID_FILTER_DESCENDANTS           33752
#define ID_FILTER_SPOUSES               33753
#define ID_FILTER_FATHERS               33754
#define ID_FILTER_MOTHERS               33755
#define ID_FILTER_SPOUSESPOUSES         33756
#define ID_MARRIAGES_DESCENDANTS        33760
#define ID_MARRIAGES_SPOUSES            33761
#define ID_MARRIAGES_PARENTS            33762
#define ID_EDIT_DATABASE                33781
#define ID_GROUPBY_BIRTHDATE            33829
#define ID_GROUPBY_DEATHDATE            33832
#define ID_GROUPBY_COMMENT              33834
#define ID_BRACKETS_ROUND               33865
#define ID_BRACKETS_SQUARE              33866
#define ID_FILTER_D_AG                  33873
#define ID_FILTER_D_TORZS               33874
#define ID_FILTER_D_OTHER               33877
#define ID_FILTER_D_VONAL               33893
#define ID_FILTER_D_OS                  33894
#define ID_FILTER_D_CSALAD              33895
#define ID_FILTER_D_ALL                 33904
#define ID_FILTER_MIND_AG               33913
#define ID_FILTER_F_OTHER               33915
#define ID_FILTER_T_OTHER               33917
#define ID_FILTER_D_ADOPT               33918
#define ID_FILTER_MIND_TORZS            33920
#define ID_FILTER_MIND_ADOPT            33921
#define ID_FILTER_MIND_VONAL            33922
#define ID_FILTER_MIND_OS               33923
#define ID_FILTER_MIND_CSALAD           33924
#define ID_FILTER_MIND_OTHER            33925
#define ID_FILTER_MIND_ALL              33926
#define ID_FILTER_F_ALL                 33927
#define ID_FILTER_F_TORZS               33928
#define ID_FILTER_F_AG                  33929
#define ID_FILTER_T_ALL                 33930
#define ID_FILTER_T_VONAL               33931
#define ID_FILTER_T_AG                  33932
#define ID_FILTER_R_FAMILY              33933
#define ID_FILTER_R_TABLE               33934
#define ID_R_DESC_ALL                   33941
#define ID_R_DESC_RELATIVES             33945
#define ID_R_DESC_OTHER                 33947
#define ID_FILTER_R_ALL                 33949
#define ID_HTML_EDIT                    33975
#define ID_HTML_NOTEPAD                 34005
#define ID_GIVENNAME                    34045
#define ID_ASCENDANTS                   34052
#define ID_HUSBAND_WIFE                 34054
#define ID_CSALAD_TORZS                 34062
#define ID_CHECK_MOTHERDEATH            34064
#define ID_CHECK_LIFESPAN               34073
#define ID_DATEFORMAT                   34075
#define ID_INPUT_MANUAL                 34094
#define ID_GEDCOM_TAGS                  34114
#define ID_GEDCOM_INPUT                 34122
#define ID_LIST_LINES                   34132
#define ID_DESCENDANTS_SELECTED         34138
#define ID_CHECK_FATHER9                34146
#define ID_LIST                         34148
#define ID_RESET                        34151
#define ID_CHECK_SPOUSEDIFF             34164
#define ID_FATHERCHILD_GREATER          34171
#define ID_FATHERCHILD_LESS             34172
#define ID_MOTHERCHILD_GREATER          34173
#define ID_MOTHERCHILD_LESS             34174
#define ID_HUSBAND_AGE_G                34178
#define ID_HUSBAND_AGE_L                34179
#define ID_WIFE_AGE_G                   34182
#define ID_WIFE_AGE_L                   34184
#define ID_CHECK_SPOUSES_SEX            34185
#define ID_SAMENAMEANDMOTHER2           34191
#define ID_SAMENAMEANDFATHER2           34192
#define ID_SAMENAMEANDBIRTH2            34193
#define ID_SAMENAMEANDDEATH2            34194
#define ID_HTML                         34195
#define ID_CHECK_SAMESPOUSENAME         34199
#define ID_CHECK_SAMENAMES_SPOUSES      34201
#define ID_LIST_PEOPLEANDFAMILY         34203
#define ID_ERRORFILE1                   34216
#define ID_ERRORFILE2                   34217
#define ID_ERRORFILE4                   34218
#define ID_ERRORFILE3                   34219
#define ID_NAME_PROBLEMS                34223
#define ID_CHECK_MOTHERINDEX            34225
#define ID_FILTER_NAME                  34234
#define ID_FILTER_TABLES                34236
#define ID_DISPLAY_BLOB                 34243
#define ID_FILTER_PEOPLE                34246
#define ID_EDIT_DELETEM                 34251
#define ID_EDIT_INSERTM                 34253
#define ID_EDIT_UPDATEM                 34255
#define ID_FILTER_MARRIAGES             34256
#define ID_FILTER_ONEPEOPLE             34260
#define ID_EMAIL                        34262
#define ID_GEDCOM_OUTPUT                34271
#define ID_MENT_SELECTED                34278
#define ID_MENT_ALL                     34279
#define ID_ATTESZ                       34281
#define ID_EDIT_GYEREK                  34286
#define ID_LINE_HUSBAND                 34322
#define ID_LINE_WIFE                    34324
#define ID_CHECK_INEGRITY               34332
#define ID_CHECK_GENERATIONS            34336
#define ID_UJLISTA                      34381
#define ID_CONTRACTEDCOUPLES            34387
#define ID_CONTRACT_PEOPLE              34399
#define ID_FAMILYDATES                  34423
#define ID_HTML_NOTEPAD_PARENTS         34429
#define ID_HTML_FATHERANDSIBLINGS       34433
#define ID_LISTA                        34446
#define ID_PARAMETERS                   34455
#define ID_DISPLAY_FAMILIES             34462
#define ID_EDIT_3GENERATIONS            34466
#define ID_INFO_FAMILIES                34470
#define ID_FILTER_FATHER9               34472
#define ID_FILTER_UNFILTERED            34474
#define ID_FILTER_MOTHERAGE             34480
#define ID_FILTER_BEFOREFATHER          34486
#define ID_FILTER_BIRTHDEATH            34489
#define ID_FILTER_BIRTH                 34491
#define ID_FILTER_DEATH                 34493
#define ID_FILTER_WEDDING               34495
#define ID_BORNAFTERHDEATH              34497
#define ID_BORNBEFORE_MBIRTH            34500
#define ID_DIEDBEFORE_MBIRTH            34501
#define ID_BORNAFTERMOTHERDEATH         34503
#define ID_LIFESPAN                     34505
#define ID_HTML_CHILDREN                34507
#define ID_CHECK_WEDDINGDATE            34522
#define ID_ASCESTOR                     34527
#define ID_DESCENDANTS                  34529
#define ID_SET_ANCESTOR                 34534
#define ID_RELATIVES                    34536
#define ID_EDIT_MARRIAGE                34545
#define ID_UNREFERENCED_ITEMS           34550
#define ID_DESCENDANTS_ALL              34556
#define ID_CHECK_FOLYT                  34569
#define ID_OL_LIST                      34584
#define ID_FATHER_SAMECHILDREN          34594
#define ID_ROKONSAG                     34606
#define ID_CHECK_NUMOFSPOUSES           34608
#define ID_CHECK_ORDERWIFE              34610
#define ID_CHECK_NUMOFCHILDREN          34613
#define ID_UNITE_DATA                   34615
#define ID_UNITED_NOTUNITED             34617
#define ID_UNITED_LISTS                 34619
#define ID_INPUTGA                      34623
#define ID_CHECK_FAMILYDATES            34635
#define ID_CHECK_NAMES                  34637
#define ID_CHECK_DATEFORMAT             34638
#define ID_INPUT_GEDCOM                 34641
#define ID_LIST_HEAD                    34661
#define ID_LIST_ZEROLEVEL               34665
#define ID_LIST_FILE                    34666
#define ID_LIST_CHAIN                   34675
#define ID_LIST_FILE_TAB                34678
#define ID_FILTER_IRREGULAR             34681
#define ID_FOLYT_LINES                  34682
#define ID_GA_EDITOR                    34685
#define ID_GA_OPEN                      34686
#define ID_REPEATED_FAMILIES            34689
#define ID_FILTER_TABLE_ANCESTORS       34708
#define ID_FILTER_FAMILY_ANCESTORS      34710
#define ID_GROUPBY_POSTERIOR            34716
#define ID_CHECK_PARENTS                34720
#define ID_FIRSTNAMES                   34722
#define ID_DB_EDIT                      34724
#define ID_UNITE                        34727
#define ID_ROUND_BRACKETS               34733
#define ID_NOIDENTIFICATION             34734
#define ID_BRACES_BRACKETS              34736
#define ID_UNFILTERED                   34741
#define ID_WRONG_BRACKETS               34742
#define ID_BRACKETS_FAMILY              34744
#define ID_BRACKETS_TABLE               34745
#define ID_BRACKETS_GOOD                34747
#define ID_BRACKETS_TORZS               34750
#define ID_BRACKETS_AG                  34753
#define ID_BRACKETS_DESC                34755
#define ID_EDIT_NOTEPAD                 34758
#define ID_GITHUB                       34760
#define ID_ALLMARRIAGES                 34766
#define ID_1WIFE                        34777
#define ID_8WIFES                       34784
#define ID_7WIFES                       34785
#define ID_6WIFES                       34786
#define ID_5WIFES                       34787
#define ID_4WIFES                       34788
#define ID_3WIFES                       34789
#define ID_2WIFES                       34790
#define ID_9WIFES                       34791
#define ID_10WIFES                      34792
#define ID_ROWIDMARRIAGES               34794
#define ID_MARRIAGES_MAN                34797
#define ID_MARRIAGES_ALL                34799
#define ID_MARRIAGES_WOMAN              34801
#define ID_COMPARE_WIFES                34806
#define ID_COMPARE_HUSBANDS             34807
#define ID_NOTPAD_WIFE                  34810
#define ID_NOTEPAD_HUSBAND              34811
#define ID_HTML_HUSBAND                 34812
#define ID_HTML_WIFES                   34814
#define ID_COMPARE_2PEOPLE              34817
#define ID_KEKULE                       34820
#define ID_COMPARE_ASC                  34822
#define ID_VERSIONS                     34828
#define ID_UNITE_ENTRIES                34836
#define ID_SELECT_HTML                  34841
#define ID_DESCENDANTS_NEW              34842
#define ID_TABLE_DESCENDANTS            34848
#define ID_CONTRACT_ENTRIES             34864
#define ID_RICHEDIT                     34866
#define ID_FILTER_ITERATION1            34870
#define ID_FILTER_ITERATION2            34872
#define ID_ATVETT                       34874
#define ID_UNITE2                       34887
#define ID_FILTER_BY_NAME               34889
#define ID_INFO_UNION                   34892
#define ID_INFO_UNITED                  34893
#define ID_UNITEDENTRIES                34894
#define ID_COMPARE_ASCENDANTS           34896
#define ID_FILTER_BY_MOTHER             34898
#define ID_GEDCOM_CELECT                34902
#define ID_GAHTML_SELECT                34904
#define ID_GAHTML_EDITOR                34905
#define ID_GAHTML_OPEN                  34906
#define ID_GAHTML_DESCENDANT_FILE       34907
#define ID_GAHTML_DESCENDANT_TABLE      34908
#define ID_GAHTML_DESCENDANT_LINE       34909
#define ID_GAHTML_MARRIAGES_FILE        34910
#define ID_GAHTML_MARRIAGES_TABLE       34911
#define ID_GAHTML_MARRIAGES_LINE        34912
#define ID_GAHTML_SS_FILE               34913
#define ID_GAHTML_SS_TABLE              34914
#define ID_GAHTML_SS_LINE               34915
#define ID_GAHTML_ROUND_BRACKETS        34916
#define ID_GAHTML_SQUARE_BRACKETS       34917
#define ID_GAHTML_BRACES_BRACKETS       34918
#define ID_GAHTML_CHECH_FOLYT           34922
#define ID_BRACKETS_BRACES              34923
#define ID_EDIT_SORAGA                  34926
#define ID_MARRIGE_GEDCOM               34928
#define ID_MARRAIGES2                   34930
#define ID_ROKONOK                      34933
#define ID_INFO_VERSION                 34937
#define ID_FUNCTIONS_KERESS             34940
#define ID_FUNCTIONS_NEXT               34942
#define ID_KERESS_BEGINNING             34946
#define ID_KERESS_NEXT                  34947
#define ID_KERESS_PREVIOUS              34948
#define ID_FUNCTIONS_DESCENDANDS        34950
#define ID_FUNCTIONS_ASCENDANTS         34952
#define ID_HTMLLISTA                    34953
#define ID_HTMLLISTA_FIX                34956
#define ID_HTMLLISTA_PRINTABLE          34957
#define ID_PIRAMIS                      34958
#define ID_GRID                         34959
#define ID_CONNECT                      34960
#define ID_SAVE                         34961
#define ID_OPEN                         34962
#define ID_LISTS_ALL                    34963
#define ID_MARRIAGES                    34964
#define ID_UNITE_SAMENAME               34965
#define ID_INFO_DB                      34966
#define ID_FAMILIES                     34967
#define ID_STATIC                       34968
#define ID_BROWSE                       34970
#define ID_NOTEPAD                      34971
#define ID_DESCENDANTS_FILE             34972
#define ID_DESCENDANTS_LINE             34973
#define ID_UNITE_SAMENAMENOT            34974
#define ID_GEDCOM_LIST                  34975
#define ID_SPOUSES_FILE                 34976
#define ID_SPOUSES_TABLE                34977
#define ID_SPOUSES_LINE                 34978
#define ID_HTML_INFO                    34979
#define ID_UNITE_INFO                   34987
#define ID_UNION_SHOW                   34988
#define ID_CHECK_SAMENAME_SAMEFATHERNAME 34988
#define IDC_STYLE                       34992
#define ID_GEDCOM_INFO                  34995
#define ID_CHECK_SAMENAME_SAMEBIRTH     34995
#define ID_GEDCOM_LIST_TAB              34996
#define ID_GEDCOM_LEVEL0                34998
#define ID_GEDCOM_CHAIN                 34999
#define ID_GEDCOM_KNOWN_UNKNOWN         35000
#define ID_GEDCOM_FILTER                35001
#define ID_CHECK_SAMENAME_SAMEMOTHERNAME 35002
#define ID_CHECK_SAMENAME_SAMEDEATH     35003
#define ID_COUPLES_DIFFERENTWDATES      35005
#define ID_CHECK_REFERENCES             35006
#define ID_CHECK_UNREFERENCED           35007
#define ID_CHECK_UNKNOWN_NAMES          35008
#define ID_DATES_VALID                  35009
#define ID_DATES_FAMILY                 35010
#define ID_CHECK_SPOUSEDATES            35012
#define ID_FATHERANDCHILD               35014
#define ID_MOTHERANDCHILD               35015
#define ID_BORN_AFTERMOTHERDEATH        35016
#define ID_BORN_AFTERFATHERDEATH        35017
#define ID_CHECK_HUSBANDAGE             35018
#define ID_CHECK_WIFEAGE                35019
#define ID_CHECK_SPOUSESEX              35020
#define ID_CHECK_GENERATIONCODE         35022
#define ID_CHECK_REPEATED_FAMILIES      35025
#define ID_BUTTON                       35028
#define ID_MARRIAGE_ALL                 35037
#define ID_MARRIAGE_ROWID               35038
#define ID_MARRIAGE_NAME                35039
#define ID_BUTTON2                      35040
#define ID_AVERAGE_LIFESPAN             35040
#define ID_MEGJELEN35041                35041
#define ID_BIRTH_DEATH                  35042
#define ID_EDIT_KERSZTN35043            35043
#define ID_EDIT_KERSZTNEV               35044
#define ID_EDIT_GA                      35045
#define ID_EDIT_GA35046                 35046
#define ID_EDIT_SPLIT                   35047
#define ID_MEGJELEN35048                35048
#define ID_K35049                       35049
#define ID_K35050                       35050
#define ID_K35051                       35051
#define ID_K35052                       35052
#define ID_GROUP_MPLACE                 35053
#define ID_GROUP_MDATA                  35054
#define ID_GROUP_MDATE                  35055
#define ID_GROUP_HUSBAND                35056
#define ID_GROUP_WIFE                   35057
#define ID_LESZ35058                    35058
#define ID_INDENTED_LIST                35059
#define ID_TABUL35060                   35060
#define ID_INDENTED_ASCENDANTS          35061
#define ID_FUNCTIONS_NOTEPAD            35062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        577
#define _APS_NEXT_COMMAND_VALUE         35063
#define _APS_NEXT_CONTROL_VALUE         1854
#define _APS_NEXT_SYMED_VALUE           387
#endif
#endif
